from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime

class MetaInsightData(BaseModel):
    """Schema for nested 'data' field."""
    objective: Optional[str] = Field(None, description="The campaign objective")
    spend: Optional[float] = Field(0, description="The amount spent")
    impressions: Optional[float] = Field(0, description="The number of impressions")
    clicks_all: Optional[float] = Field(0, description="The number of clicks")
    cpc_all: Optional[float] = Field(0, description="The cost per click")
    link_click: Optional[float] = Field(0, description="The number of link clicks")
    cpc_link_click: Optional[float] = Field(0, description="The cost per link click")
    ctr_all: Optional[float] = Field(0, description="The click-through rate")
    ctr_rate: Optional[float] = Field(0, description="The click-through rate")
    cpm: Optional[float] = Field(0, description="The cost per 1000 impressions")
    landing_page_view: Optional[float] = Field(0, description="The number of landing page views")
    add_to_cart: Optional[float] = Field(0, description="The number of add to carts")
    add_to_cart_value: Optional[float] = Field(0, description="The value of add to carts")
    cost_per_add_to_cart: Optional[float] = Field(0, description="The cost per add to cart")
    purchase: Optional[float] = Field(0, description="The number of purchases")
    purchase_value: Optional[float] = Field(0, description="The value of purchases")
    cost_per_purchase: Optional[float] = Field(0, description="The cost per purchase")
    roas: Optional[float] = Field(0, description="The return on ad spend")
    avg_basket_price: Optional[float] = Field(0, description="The average basket price")
    initiate_checkout: Optional[float] = Field(0, description="The number of initiate checkouts")
    lead: Optional[float] = Field(0, description="The number of leads")
    cost_per_lead: Optional[float] = Field(0, description="The cost per lead")
    application_submitted: Optional[float] = Field(0, description="The number of applications submitted")
    registration_completed: Optional[float] = Field(0, description="The number of registrations completed")
    estimated_ad_recallers: Optional[float] = Field(0, description="The number of estimated ad recallers")
    post_saves: Optional[float] = Field(0, description="The number of post saves")
    post_reaction: Optional[float] = Field(0, description="The number of post reactions")
    post_comment: Optional[float] = Field(0, description="The number of post comments")
    post_share: Optional[float] = Field(0, description="The number of post shares")
    post_engagement: Optional[float] = Field(0, description="The number of post engagements")
    add_to_cart_shared_item: Optional[float] = Field(0, description="The number of add to carts for shared items")
    add_to_cart_value_shared_item: Optional[float] = Field(0, description="The value of add to carts for shared items")
    cost_per_add_to_cart_shared_item: Optional[float] = Field(0, description="The cost per add to cart for shared items")
    purchase_shared_item: Optional[float] = Field(0, description="The number of purchases for shared items")
    purchase_value_shared_item: Optional[float] = Field(0, description="The value of purchases for shared items")
    cost_per_purchase_shared_item: Optional[float] = Field(0, description="The cost per purchase for shared items")
    content_view_shared_item: Optional[float] = Field(0, description="The number of content views for shared items")
    content_view_value_shared_item: Optional[float] = Field(0, description="The value of content views for shared items")
    roas_shared_item: Optional[float] = Field(0, description="The return on ad spend for shared items")
    funnel_landing_page_view_to_add_to_cart:Optional[float] = Field(0, description="The funnel from landing page view to add to cart")
    funnel_add_to_cart_to_initiate_checkout:Optional[float] = Field(0, description="The funnel from add to cart to initiate checkout")
    funnel_initiate_checkout_to_purchase:Optional[float] = Field(0, description="The funnel from initiate checkout to purchase")
    funnel_add_to_cart_to_purchase:Optional[float] = Field(0, description="The funnel from add to cart to purchase")
    application_submitted_custom: Optional[float] = Field(0, description="The number of applications submitted")
    messaging_new: Optional[float] = Field(0, description="The number of new messaging conversations")
    messaging_blocked: Optional[float] = Field(0, description="The number of blocked messaging conversations")
    messaging_conv_started: Optional[float] = Field(0, description="The number of messaging conversations started")

class MetaInsight(BaseModel):
    """Schema for the main document."""
    ad_account: str = Field(..., description="The ID of the ad account")
    campaign_name: str = Field(..., description="The name of the campaign")
    campaign_id: str = Field(..., description="The ID of the campaign")
    date: datetime = Field(..., description="The date of the data")
    date_inserted: datetime = Field(default_factory=datetime.utcnow, description="The timestamp when the data was inserted")
    objective: Optional[str] = Field(None, description="The campaign objective")
    data: MetaInsightData = Field(..., description="Nested data containing metrics")

class MetaReference(BaseModel):
    """Schema for the reference document."""
    account_id: str = Field(..., description="The ID of the account")
    access_token: str = Field(..., description="The access token")
    level: str = Field(..., description="The level of the data")
    reference: str = Field(..., description="The reference ID")
    date_start: str = Field(..., description="The start date of the data")
    date_end: str = Field(..., description="The end date of the data")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="The timestamp when the data was inserted")
