from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime

class TikTokInsightData(BaseModel):
    objective : Optional[str] = Field(None, title="Objective")
    spend : Optional[float] = Field(0, title="Spend")
    billed_cost : Optional[float] = Field(0, title="Billed Cost")
    cash_spend : Optional[float] = Field(0, title="Cash Spend")
    impressions : Optional[int] = Field(0, title="Impressions")
    gross_impressions : Optional[int] = Field(0, title="Gross Impressions")
    clicks : Optional[int] = Field(0, title="Clicks")
    conversion : Optional[int] = Field(0, title="Conversion")
    real_time_conversion : Optional[int] = Field(0, title="Real Time Conversion")
    video_play_actions : Optional[int] = Field(0, title="Video Play Actions")
    video_watched_2s : Optional[int] = Field(0, title="Video Watched 2s")
    video_watched_6s : Optional[int] = Field(0, title="Video Watched 6s")
    engaged_view : Optional[int] = Field(0, title="Engaged View")
    engaged_view_15s : Optional[int] = Field(0, title="Engaged View 15s")
    video_views_p25 : Optional[int] = Field(0, title="Video Views P25")
    video_views_p50 : Optional[int] = Field(0, title="Video Views P50")
    video_views_p75 : Optional[int] = Field(0, title="Video Views P75")
    video_views_p100 : Optional[int] = Field(0, title="Video Views P100")
    engagements : Optional[int] = Field(0, title="Engagements")
    follows : Optional[int] = Field(0, title="Follows")
    likes :  Optional[int] = Field(0, title="Likes")
    comments : Optional[int] = Field(0, title="Comments")
    shares : Optional[int] = Field(0, title="Shares")
    profile_visits : Optional[int] = Field(0, title="Profile Visits")
    clicks_on_music_disc : Optional[int] = Field(0, title="Clicks on Music Disc")
    duet_clicks : Optional[int] = Field(0, title="Duet Clicks")
    stitch_clicks : Optional[int] = Field(0, title="Stitch Clicks")
    sound_usage_clicks : Optional[int] = Field(0, title="Sound Usage Clicks")
    anchor_clicks : Optional[int] = Field(0, title="Anchor Clicks")
    clicks_on_hashtag_challenge : Optional[int] = Field(0, title="Clicks on Hashtag Challenge")
    ix_video_views : Optional[int] = Field(0, title="IX Video Views")
    ix_video_views_p25 : Optional[int] = Field(0, title="IX Video Views P25")
    ix_video_views_p50 : Optional[int] = Field(0, title="IX Video Views P50")
    ix_video_views_p75 : Optional[int] = Field(0, title="IX Video Views P75")
    ix_video_views_p100 : Optional[int] = Field(0, title="IX Video Views P100")
    tt_playlist_visit : Optional[int] = Field(0, title="TT Playlist Visit")
    interactive_add_on_impressions : Optional[int] = Field(0, title="Interactive Add On Impressions")
    interactive_add_on_destination_clicks : Optional[int] = Field(0, title="Interactive Add On Destination Clicks")
    interactive_add_on_activity_clicks : Optional[int] = Field(0, title="Interactive Add On Activity Clicks")
    interactive_add_on_option_a_clicks : Optional[int] = Field(0, title="Interactive Add On Option A Clicks")
    interactive_add_on_option_b_clicks : Optional[int] = Field(0, title="Interactive Add On Option B Clicks")
    countdown_sticker_recall_clicks : Optional[int] = Field(0, title="Countdown Sticker Recall Clicks")
    live_views : Optional[int] = Field(0, title="Live Views")
    live_unique_views : Optional[int] = Field(0, title="Live Unique Views")
    live_effective_views : Optional[int] = Field(0, title="Live Effective Views")
    live_product_clicks : Optional[int] = Field(0, title="Live Product Clicks")
    real_time_app_install : Optional[int] = Field(0, title="Real Time App Install")
    real_time_app_install_cost : Optional[float] = Field(0, title="Real Time App Install Cost")
    app_install : Optional[int] = Field(0, title="App Install")
    registration : Optional[int] = Field(0, title="Registration") 
    total_registration : Optional[int] = Field(0, title="Total Registration")
    purchase : Optional[int] = Field(0, title="Purchase")
    total_purchase : Optional[int] = Field(0, title="Total Purchase")
    value_per_total_purchase : Optional[float] = Field(0, title="Value Per Total Purchase")
    total_purchase_value : Optional[float] = Field(0, title="Total Purchase Value")
    app_event_add_to_cart : Optional[int] = Field(0, title="App Event Add To Cart")
    total_app_event_add_to_cart : Optional[int] = Field(0, title="Total App Event Add To Cart")
    value_per_total_app_event_add_to_cart : Optional[float] = Field(0, title="Value Per Total App Event Add To Cart")
    total_app_event_add_to_cart_value : Optional[float] = Field(0, title="Total App Event Add To Cart Value")
    checkout : Optional[int] = Field(0, title="Checkout")
    total_checkout : Optional[int] = Field(0, title="Total Checkout")
    value_per_checkout : Optional[float] = Field(0, title="Value Per Checkout")
    total_checkout_value : Optional[float] = Field(0, title="Total Checkout Value")
    view_content : Optional[int] = Field(0, title="View Content")
    total_view_content : Optional[int] = Field(0, title="Total View Content")
    value_per_total_view_content : Optional[float] = Field(0, title="Value Per Total View Content")
    total_view_content_value : Optional[float] = Field(0, title="Total View Content Value")
    next_day_open : Optional[int] = Field(0, title="Next Day Open")
    total_next_day_open : Optional[int] = Field(0, title="Total Next Day Open")
    add_payment_info : Optional[int] = Field(0, title="Add Payment Info")
    total_add_payment_info : Optional[int] = Field(0, title="Total Add Payment Info")
    add_to_wishlist : Optional[int] = Field(0, title="Add To Wishlist")
    total_add_to_wishlist : Optional[int] = Field(0, title="Total Add To Wishlist")
    value_per_total_add_to_wishlist : Optional[float] = Field(0, title="Value Per Total Add To Wishlist")
    total_add_to_wishlist_value : Optional[float] = Field(0, title="Total Add To Wishlist Value")
    launch_app : Optional[int] = Field(0, title="Launch App")
    total_launch_app : Optional[int] = Field(0, title="Total Launch App")
    complete_tutorial : Optional[int] = Field(0, title="Complete Tutorial")
    total_complete_tutorial : Optional[int] = Field(0, title="Total Complete Tutorial")
    value_per_total_complete_tutorial : Optional[float] = Field(0, title="Value Per Total Complete Tutorial")
    total_complete_tutorial_value : Optional[float] = Field(0, title="Total Complete Tutorial Value")
    create_group : Optional[int] = Field(0, title="Create Group")
    total_create_group : Optional[int] = Field(0, title="Total Create Group")
    value_per_total_create_group : Optional[float] = Field(0, title="Value Per Total Create Group")
    total_create_group_value : Optional[float] = Field(0, title="Total Create Group Value")
    join_group : Optional[int] = Field(0, title="Join Group")
    total_join_group : Optional[int] = Field(0, title="Total Join Group")
    value_per_total_join_group : Optional[float] = Field(0, title="Value Per Total Join Group")
    total_join_group_value : Optional[float] = Field(0, title="Total Join Group Value")
    create_gamerole : Optional[int] = Field(0, title="Create Gamerole")
    total_create_gamerole : Optional[int] = Field(0, title="Total Create Gamerole")
    value_per_total_create_gamerole : Optional[float] = Field(0, title="Value Per Total Create Gamerole")
    total_create_gamerole_value : Optional[float] = Field(0, title="Total Create Gamerole Value")
    spend_credits : Optional[int] = Field(0, title="Spend Credits")
    total_spend_credits : Optional[int] = Field(0, title="Total Spend Credits")
    value_per_total_spend_credits : Optional[float] = Field(0, title="Value Per Total Spend Credits")
    total_spend_credits_value : Optional[float] = Field(0, title="Total Spend Credits Value")
    achieve_level : Optional[int] = Field(0, title="Achieve Level")
    total_achieve_level : Optional[int] = Field(0, title="Total Achieve Level")
    value_per_total_achieve_level : Optional[float] = Field(0, title="Value Per Total Achieve Level")
    total_achieve_level_value : Optional[float] = Field(0, title="Total Achieve Level Value")
    unlock_achievement : Optional[int] = Field(0, title="Unlock Achievement")
    total_unlock_achievement : Optional[int] = Field(0, title="Total Unlock Achievement")
    value_per_total_unlock_achievement : Optional[float] = Field(0, title="Value Per Total Unlock Achievement")
    total_unlock_achievement_value : Optional[float] = Field(0, title="Total Unlock Achievement Value")
    sales_lead : Optional[int] = Field(0, title="Sales Lead")
    total_sales_lead : Optional[int] = Field(0, title="Total Sales Lead")
    value_per_total_sales_lead : Optional[float] = Field(0, title="Value Per Total Sales Lead")
    total_sales_lead_value : Optional[float] = Field(0, title="Total Sales Lead Value")
    in_app_ad_click : Optional[int] = Field(0, title="In App Ad Click")
    total_in_app_ad_click : Optional[int] = Field(0, title="Total In App Ad Click")
    value_per_total_in_app_ad_click : Optional[float] = Field(0, title="Value Per Total In App Ad Click")
    total_in_app_ad_click_value : Optional[float] = Field(0, title="Total In App Ad Click Value")
    in_app_ad_impr : Optional[int] = Field(0, title="In App Ad Impr")
    total_in_app_ad_impr : Optional[int] = Field(0, title="Total In App Ad Impr")
    value_per_total_in_app_ad_impr : Optional[float] = Field(0, title="Value Per Total In App Ad Impr")
    total_in_app_ad_impr_value : Optional[float] = Field(0, title="Total In App Ad Impr Value")
    loan_apply : Optional[int] = Field(0, title="Loan Apply")
    total_loan_apply : Optional[int] = Field(0, title="Total Loan Apply")
    loan_credit : Optional[int] = Field(0, title="Loan Credit")
    total_loan_credit : Optional[int] = Field(0, title="Total Loan Credit")
    loan_disbursement : Optional[int] = Field(0, title="Loan Disbursement")
    total_loan_disbursement : Optional[int] = Field(0, title="Total Loan Disbursement")
    total_login : Optional[int] = Field(0, title="Total Login")
    ratings : Optional[int] = Field(0, title="Ratings")
    total_ratings : Optional[int] = Field(0, title="Total Ratings")
    value_per_total_ratings : Optional[float] = Field(0, title="Value Per Total Ratings")
    total_ratings_value : Optional[float] = Field(0, title="Total Ratings Value")
    search : Optional[int] = Field(0, title="Search")
    total_search : Optional[int] = Field(0, title="Total Search")
    start_trial : Optional[int] = Field(0, title="Start Trial")
    total_start_trial : Optional[int] = Field(0, title="Total Start Trial")
    subscribe : Optional[int] = Field(0, title="Subscribe")
    total_subscribe : Optional[int] = Field(0, title="Total Subscribe")
    value_per_total_subscribe : Optional[float] = Field(0, title="Value Per Total Subscribe")
    total_subscribe_value : Optional[float] = Field(0, title="Total Subscribe Value")
    unique_custom_app_events : Optional[int] = Field(0, title="Unique Custom App Events")
    custom_app_events : Optional[int] = Field(0, title="Custom App Events")
    value_per_custom_app_event : Optional[float] = Field(0, title="Value Per Custom App Event")
    custom_app_events_value : Optional[float] = Field(0, title="Custom App Events Value")
    unique_ad_impression_events : Optional[int] = Field(0, title="Unique Ad Impression Events")
    ads_impression_events : Optional[int] = Field(0, title="Ads Impression Events")
    value_per_ad_impression_event : Optional[float] = Field(0, title="Value Per Ad Impression Event")
    total_ad_impression_events_value : Optional[float] = Field(0, title="Total Ad Impression Events Value")
    vta_conversion : Optional[int] = Field(0, title="VTA Conversion")
    vta_app_install : Optional[int] = Field(0, title="VTA App Install")
    vta_registration : Optional[int] = Field(0, title="VTA Registration")
    vta_purchase : Optional[int] = Field(0, title="VTA Purchase")
    vta_complete_payment : Optional[int] = Field(0, title="VTA Complete Payment")
    vta_complete_payment_value : Optional[float] = Field(0, title="VTA Complete Payment Value")
    cta_conversion : Optional[int] = Field(0, title="CTA Conversion")
    cta_app_install : Optional[int] = Field(0, title="CTA App Install")
    cta_registration : Optional[int] = Field(0, title="CTA Registration")
    cta_purchase : Optional[int] = Field(0, title="CTA Purchase")
    engaged_view_through_conversions :  Optional[int] = Field(0, title="Engaged View Through Conversions")
    evta_app_install : Optional[int] = Field(0, title="EVTA App Install")
    evta_registration : Optional[int] = Field(0, title="EVTA Registration")
    evta_purchase : Optional[int] = Field(0, title="EVTA Purchase")
    evta_payments_completed : Optional[int] = Field(0, title="EVTA Payments Completed")
    complete_payment : Optional[int] = Field(0, title="Complete Payment")
    value_per_complete_payment : Optional[float] = Field(0, title="Value Per Complete Payment")
    total_landing_page_view : Optional[int] = Field(0, title="Total Landing Page View")
    total_pageview : Optional[int] = Field(0, title="Total Pageview")
    total_value_per_pageview : Optional[float] = Field(0, title="Total Value Per Pageview")
    button_click : Optional[int] = Field(0, title="Button Click")
    value_per_button_click : Optional[float] = Field(0, title="Value Per Button Click")
    total_button_click_value : Optional[float] = Field(0, title="Total Button Click Value")
    online_consult : Optional[int] = Field(0, title="Online Consult")
    value_per_online_consult : Optional[float] = Field(0, title="Value Per Online Consult")
    total_online_consult_value : Optional[float] = Field(0, title="Total Online Consult Value")
    user_registration : Optional[int] = Field(0, title="User Registration")
    value_per_user_registration : Optional[float] = Field(0, title="Value Per User Registration")
    total_user_registration_value : Optional[float] = Field(0, title="Total User Registration Value")
    page_content_view_events : Optional[int] = Field(0, title="Page Content View Events")
    value_per_page_content_view_event : Optional[float] = Field(0, title="Value Per Page Content View Event")
    total_page_view_content_events_value : Optional[float] = Field(0, title="Total Page View Content Events Value")
    product_details_page_browse : Optional[int] = Field(0, title="Product Details Page Browse")
    value_per_product_details_page_browse : Optional[float] = Field(0, title="Value Per Product Details Page Browse")
    total_product_details_page_browse_value : Optional[float] = Field(0, title="Total Product Details Page Browse Value")
    web_event_add_to_cart : Optional[int] = Field(0, title="Web Event Add To Cart")
    value_per_web_event_add_to_cart : Optional[float] = Field(0, title="Value Per Web Event Add To Cart")
    total_web_event_add_to_cart_value : Optional[float] = Field(0, title="Total Web Event Add To Cart Value")
    on_web_order : Optional[int] = Field(0, title="On Web Order")
    value_per_on_web_order : Optional[float] = Field(0, title="Value Per On Web Order")
    total_on_web_order_value : Optional[float] = Field(0, title="Total On Web Order Value")
    initiate_checkout : Optional[int] = Field(0, title="Initiate Checkout")
    value_per_initiate_checkout : Optional[float] = Field(0, title="Value Per Initiate Checkout")
    total_initiate_checkout_value : Optional[float] = Field(0, title="Total Initiate Checkout Value")
    add_billing : Optional[int] = Field(0, title="Add Billing")
    value_per_add_billing : Optional[float] = Field(0, title="Value Per Add Billing")
    total_add_billing_value : Optional[float] = Field(0, title="Total Add Billing Value")
    page_event_search : Optional[int] = Field(0, title="Page Event Search")
    value_per_page_event_search : Optional[float] = Field(0, title="Value Per Page Event Search")
    total_page_event_search_value : Optional[float] = Field(0, title="Total Page Event Search Value")
    form : Optional[int] = Field(0, title="Form")
    value_per_form : Optional[float] = Field(0, title="Value Per Form")
    download_start_rate : Optional[float] = Field(0, title="Download Start Rate")
    value_per_download_start : Optional[float] = Field(0, title="Value Per Download Start")
    total_download_start_value : Optional[float] = Field(0, title="Total Download Start Value")
    on_web_add_to_wishlist : Optional[int] = Field(0, title="On Web Add To Wishlist")
    on_web_add_to_wishlist_per_click : Optional[float] = Field(0, title="On Web Add To Wishlist Per Click")
    value_per_on_web_add_to_wishlist : Optional[float] = Field(0, title="Value Per On Web Add To Wishlist")
    total_on_web_add_to_wishlist_value : Optional[float] = Field(0, title="Total On Web Add To Wishlist Value")
    on_web_subscribe : Optional[int] = Field(0, title="On Web Subscribe")
    on_web_subscribe_per_click : Optional[float] = Field(0, title="On Web Subscribe Per Click")
    value_per_on_web_subscribe : Optional[float] = Field(0, title="Value Per On Web Subscribe")
    total_on_web_subscribe_value : Optional[float] = Field(0, title="Total On Web Subscribe Value")
    custom_page_events : Optional[int] = Field(0, title="Custom Page Events")
    value_per_custom_page_event : Optional[float] = Field(0, title="Value Per Custom Page Event")
    custom_page_events_value : Optional[float] = Field(0, title="Custom Page Events Value")
    onsite_add_to_wishlist : Optional[int] = Field(0, title="Onsite Add To Wishlist")
    value_per_onsite_add_to_wishlist : Optional[float] = Field(0, title="Value Per Onsite Add To Wishlist")
    total_onsite_add_to_wishlist_value : Optional[float] = Field(0, title="Total Onsite Add To Wishlist Value")
    onsite_add_billing : Optional[int] = Field(0, title="Onsite Add Billing")
    value_per_onsite_add_billing : Optional[float] = Field(0, title="Value Per Onsite Add Billing")
    total_onsite_add_billing_value : Optional[float] = Field(0, title="Total Onsite Add Billing Value")
    onsite_form : Optional[int] = Field(0, title="Onsite Form")
    value_per_onsite_form : Optional[float] = Field(0, title="Value Per Onsite Form")
    total_onsite_form_value : Optional[float] = Field(0, title="Total Onsite Form Value")
    onsite_download_start : Optional[int] = Field(0, title="Onsite Download Start")
    onsite_destination_visits : Optional[int] = Field(0, title="Onsite Destination Visits")
    cost_per_onsite_destination_visit : Optional[float] = Field(0, title="Cost Per Onsite Destination Visit")
    onsite_destination_visit_rate : Optional[float] = Field(0, title="Onsite Destination Visit Rate")
    ix_page_view_count : Optional[int] = Field(0, title="IX Page View Count")
    ix_button_click_count : Optional[int] = Field(0, title="IX Button Click Count")
    ix_product_click_count : Optional[int] = Field(0, title="IX Product Click Count")
    onsite_shopping : Optional[int] = Field(0, title="Onsite Shopping")
    value_per_onsite_shopping : Optional[float] = Field(0, title="Value Per Onsite Shopping")
    total_onsite_shopping_value : Optional[float] = Field(0, title="Total Onsite Shopping Value")
    onsite_initiate_checkout_count : Optional[int] = Field(0, title="Onsite Initiate Checkout Count")
    value_per_onsite_initiate_checkout_count : Optional[float] = Field(0, title="Value Per Onsite Initiate Checkout Count")
    total_onsite_initiate_checkout_count_value : Optional[float] = Field(0, title="Total Onsite Initiate Checkout Count Value")
    onsite_on_web_detail : Optional[int] = Field(0, title="Onsite On Web Detail")
    value_per_onsite_on_web_detail : Optional[float] = Field(0, title="Value Per Onsite On Web Detail")
    total_onsite_on_web_detail_value : Optional[float] = Field(0, title="Total Onsite On Web Detail Value")
    onsite_on_web_cart : Optional[int] = Field(0, title="Onsite On Web Cart")
    value_per_onsite_on_web_cart : Optional[float] = Field(0, title="Value Per Onsite On Web Cart")
    total_onsite_on_web_cart_value : Optional[float] = Field(0, title="Total Onsite On Web Cart Value")

class TikTokInsightDataLive(BaseModel):
    """Schema for nested 'data' field."""
    objective: Optional[str] = Field(None, description="The campaign objective")
    reach: Optional[int] = Field(0, description="The number of unique people who saw the ad")
    frequency: Optional[float] = Field(0, description="The average number of times each person saw the ad")
    cost_per_1000_reached: Optional[float] = Field(0, description="The cost to reach 1000 people")
    average_video_play: Optional[float] = Field(0, description="The average video play")
    average_video_play_per_user: Optional[float] = Field(0, description="The average video play per user")
    onsite_download_start_rate: Optional[float] = Field(0, description="The onsite download start rate")
    ix_page_duration_avg: Optional[float] = Field(0, description="The IX page duration average")
    ix_page_viewrate_avg: Optional[float] = Field(0, description="The IX page viewrate average")

class TikTokContentData(BaseModel):
    content: Optional[str] = Field(None, title="Content")
    content_expire_time: Optional[datetime] = Field(None, title="Content Expire Time")

class TikTokInsight(BaseModel):
    """Schema for the main document."""
    account_id: str = Field(..., description="The ID of the ad account")
    campaign_name: Optional[str] = Field(None, description="The name of the campaign")
    campaign_id: Optional[str] = Field(None, description="The ID of the campaign")
    adset_name: Optional[str] = Field(None, description="The name of the ad set")
    adset_id: Optional[str] = Field(None, description="The ID of the ad set")
    ad_name: Optional[str] = Field(None, description="The name of the ad")
    ad_id: Optional[str] = Field(None, description="The ID of the ad")
    date: datetime = Field(..., description="The start date of the data")
    date_inserted: datetime = Field(default_factory=datetime.utcnow, description="The timestamp when the data was inserted")
    objective: Optional[str] = Field(None, description="The campaign objective")
    data: Optional[TikTokInsightData] = Field(..., description="Nested data containing metrics")

class TikTokContent(BaseModel):
    """Schema for the main document."""
    account_id: str = Field(..., description="The ID of the ad account")
    ad_id: Optional[str] = Field(None, description="The ID of the ad")
    date_inserted: datetime = Field(default_factory=datetime.utcnow, description="The timestamp when the data was inserted")
    data: Optional[TikTokContentData] = Field(..., description="Nested data containing content")

class TikTokInsightLive(BaseModel):
    """Schema for the main document."""
    account_id: str = Field(..., description="The ID of the ad account")
    campaign_name: Optional[str] = Field(None, description="The name of the campaign")
    campaign_id: Optional[str] = Field(None, description="The ID of the campaign")
    adset_name: Optional[str] = Field(None, description="The name of the ad set")
    adset_id: Optional[str] = Field(None, description="The ID of the ad set")
    ad_name: Optional[str] = Field(None, description="The name of the ad")
    ad_id: Optional[str] = Field(None, description="The ID of the ad")
    date_start: datetime = Field(..., description="The start date of the data")
    date_end: datetime = Field(..., description="The end date of the data")
    date_inserted: datetime = Field(default_factory=datetime.utcnow, description="The timestamp when the data was inserted")
    objective: Optional[str] = Field(None, description="The campaign objective")
    data: Optional[TikTokInsightDataLive] = Field(..., description="Nested data containing metrics")